package main

import (
	"flag"
	"fmt"
	"log"
	"strconv"

	"github.com/metarsit/exchange"
	"gopkg.in/yaml.v2"
)

func main() {
	var key, secret string
	var all bool

	flag.StringVar(&key, "api", "", "API Key Generated by Crypto Exchange")
	flag.StringVar(&secret, "secret", "", "Secret Key Generated by Crypto Exchange")
	flag.BoolVar(&all, "all", true, "Show all if not only show those has non zero normal values")
	flag.Parse()

	data, err := exchange.GetAccountAPI(key, secret)
	if err != nil {
		log.Fatalln("Failed to get account api %s", err.Error())
	}

	if all == true {
		yamlFormat, err := yaml.Marshal(data)
		if err != nil {
			log.Fatalf("Enable to parse into YAML format: %s | %v", err.Error(), data)
		}
		fmt.Print(string(yamlFormat))
	} else {
		for _, detail := range data.CoinList {
			normal, _ := strconv.ParseFloat(detail.Normal, 64)
			if normal > 0 {
				fmt.Printf("%s: %f\n", detail.Name, normal)
			}
		}
	}
}
