package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"

	"github.com/metarsit/exchange"
)

func main() {
	var key, secret string

	flag.StringVar(&key, "api", "", "API Key Generated by Crypto Exchange")
	flag.StringVar(&secret, "secret", "", "Secret Key Generated by Crypto Exchange")
	flag.Parse()

	data, err := exchange.GetAccountAPI(key, secret)
	if err != nil {
		os.Exit(1)
	}

	market, err := exchange.GetMarketAPI()
	if err != nil {
		os.Exit(1)
	}

	f, err := os.OpenFile("text.log",
		os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Println(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)

	var totalValue float64
	for _, detail := range data.CoinList {
		normal, _ := strconv.ParseFloat(detail.Normal, 64)
		if normal > 0 {
			value := market[detail.Name+"usdt"] * normal
			// fmt.Printf("%s\ntotal unit: %.6f\nprice USD : %.2f\n\n", strings.ToUpper(detail.Name), normal, value)
			fmt.Fprintf(w, "%s,%.6f,%.2f,", strings.ToUpper(detail.Name), normal, value)
			totalValue += value
		}
	}
	fmt.Fprintf(w, "%.2f\n", totalValue)
	w.Flush()
}
